import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import logo from '../public/logo.svg'
import Link from 'next/link'

export default function Civis() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Civilizações Age Of Empires</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.navbar}>
        {/* <Link href='/' > */}
        <Image height={100} width={250} src={logo} alt='' />
        {/* </Link> */}
        <nav >

          <ul>
            <li>
              <Link href='/civis' >
                Civilizações
              </Link>
            </li>
            <li>
              <Link href='#' >
                Unidades
              </Link>
            </li>
            <li>
              <Link href='#' >
                Notícias
              </Link>
            </li>
            <li>
              <Link href='#' >
                Sobre
              </Link>
            </li>
          </ul>
        </nav>
        <ul>
          <li>
            Buscar
          </li>
          <li>
            Login
          </li>
        </ul>
      </header>
      <main className={styles.main}>
        <h2 style={{ background: 'white', borderRadius: '.5rem', marginTop: '.5rem', padding: '1rem', width: 'max-content', alignSelf: 'center' }}>
          Civilizações Age Of Empires II
        </h2>
        <div className={styles.banner}>


          <div className={styles.card}>
            <a
              href="https://github.com/vercel/next.js/tree/master/examples"

            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
